### PR TITLE
Escape filePath and args passed to the phpcs command

### PR DESCRIPTION
**Pull request by aslamdoctor**
Fixes issue #144 

Tested on Mac.
**Need to be tested on Windows.**

### CODE REVIEW

**Comment by jonathanbossenger** [comment]
@aslamdoctor thanks for the PR. Of course, both the filePath and the standard would need to be escaped if they're both in the same location :facepalm: I'm annoyed I missed that :grin: 

One question: in my original PR, to fix for just the [filePath](https://github.com/valeryan/vscode-phpsab/pull/139), instead of running the string through a string replace, I [wrap the string in double quotes](https://github.com/valeryan/vscode-phpsab/pull/139/files#diff-4fdfcc6a59c9f5a518efebcd885c439037d9a97257a552c050b206064a2986f6R69). This comes from my experiences in bash scripting, [where one should wrap any variables in double quotes](https://www.shellcheck.net/wiki/SC2086), to prevent scripts from breaking when input contains spaces, line feeds, glob characters and such.

I will freely admit I don't know a lot about the [node child_process spawn](https://nodejs.org/api/child_process.html#child_processspawncommand-args-options) method used to execute the phpcs command, but it seems to me that following the same process for escaping strings in the terminal made sense here. However, as it's a JavaScript code calling a method to execute the command, perhaps your solution is the better option. 

Do you have any opinions on this?

@valeryan, as the original developer, I'd also appreciate any thoughts you might have on which solution is "better"; thanks.

**Comment by valeryan** [comment]
Seems like a good solution. Makes me wish I had time to write unit test though...

**Comment by aslamdoctor** [comment]
@jonathanbossenger I was also confused why adding the double quote didn't work. It was supposed to work. It's quiet tedious to debug this. But I believe when you pass anything as **argument** to a command on terminal, it shouldn't have space and needs to be escaped with `\`.

**Comment by jonathanbossenger** [comment]
Ok, thanks for the confirming folks, let's go ahead and get this merged.

**Comment by jonathanbossenger** [comment]
> Makes me wish I had time to write unit test though...

@valeryan I hear you, but in my experience open source tools often don't get tests until someone comes along with enough time to add them. I will see if I can put some time aside for this as well.

**Comment by jonathanbossenger** [comment]
> Need to be tested on Windows.

I can test this on Windows, hopefully tomorrow.

**Comment by aslamdoctor** [comment]
Hey @jonathanbossenger no probs. Thanks for the heads up. Broken windows boot is always a pain 😔

**Comment by danieliser** [comment]
This is pretty annoying bug, any chance its getting merged/released soon?

**Comment by roosalles** [comment]
+1

**Review by jonathanbossenger — APPROVED** [review]

**Comment by yCodeTech** [comment]
This doesn't work on Windows. It just thinks it's a directory...
image

I've added a PR to revert.

**Pull request merged**
