### PR TITLE
Added new configurations to add additional arguments to phpcs and phpcbf

### PR DESCRIPTION
**Pull request by szaveri**
Feature request for #42

### CODE REVIEW

**Comment by valeryan** [comment]
This looks like a good addition.  I would like it if you would add documentation to the readme to cover these new options. In the meantime I will test this out and make sure it all works.

**Comment by szaveri** [comment]
> This looks like a good addition. I would like it if you would add documentation to the readme to cover these new options. In the meantime I will test this out and make sure it all works.

Oops! Totally forgot. I'll update the current PR

**Comment by szaveri** [comment]
@valeryan Were the README updates ok?

**Comment by valeryan** [comment]
Yeah, I have not had time to test this out yet though and I have to go remember how to push a release again.

**Comment by mchelen-gov** [comment]
would this allow `phpcs` to run on other file extensions such as `.module`?

**Comment by szaveri** [comment]
> would this allow `phpcs` to run on other file extensions such as `.module`?

Yes with the `--extensions` config but you can also run the same solution here https://github.com/squizlabs/PHP_CodeSniffer/issues/2486

`<arg name="extensions" value="php,module"/>`

which is a better solution imo.

**Pull request merged**
